// Live "team activity" feed.
//
// Derived from the central AppStore slices so the dashboard widget AND the
// notifications "Team activity" tab stay in lock-step with every real CRUD
// action the prototype performs — a new booking from the customer portal,
// a POS sale, a front-desk cancellation, a refund, a customer signup, etc.
//
// Sources (sorted newest-first, capped at MAX_TEAM_ACTIVITY rows):
//   • classBookings           — booked / waitlisted / cancelled events
//   • customerTransactions    — purchase + refund events (across pos /
//                               customer_portal / admin payment sources)
//   • customers               — new member signups
//
// Actor + description follow a stable pattern:
//   • When the action originated in the CUSTOMER PORTAL the customer IS
//     the actor — `name` = customer's display name, `description` = the
//     verb-phrase only ("Booked Reformer Pilates").
//   • When the action originated from an internal team surface
//     (front_desk / admin / pos), the customer stays the focal name
//     (every event still concerns a customer) and the team source is
//     suffixed onto the description ("Booked Reformer Pilates · via
//     Front desk") so the surface remains visually consistent.

import { useMemo } from "react";
import {
    CalendarCheck01,
    CreditCard02,
    Users01,
    UserCheck01,
    UserX01,
    SlashCircle01,
    RefreshCw04,
    Settings01,
    Tag01,
    Ticket01,
    Building01,
    Star01,
    CoinsHand,
    Announcement01,
    Edit05,
} from "@untitledui/icons";
import { useAppStore, type AuditLogEntry } from "@/lib/store";
import { relativeTime } from "@/components/notifications/notification-utils";

// All untitledui icons share the same `{ className?: string }` props
// signature — alias one of the imported icons' type so TypeScript can
// type the `icon` field on activity rows without a package-level type
// dependency that isn't actually exported.
type ActivityIcon = typeof CalendarCheck01;

export interface TeamActivityItem {
    id: string;
    /** Focal display name — the customer at the center of the event.
     *  When the row was generated by an internal team surface the team
     *  context lives in `description`, not here. */
    name: string;
    /** Human-readable relative time, e.g. "14 min ago" / "Yesterday".
     *  Pre-computed at derive time so consumers stay simple. */
    timeAgo: string;
    description: string;
    icon: ActivityIcon;
    /** Raw ISO timestamp — surfaced so consumers can re-sort, filter, or
     *  pretty-print differently if they need to. */
    createdAt: string;
}

/** Maximum rows returned by `useTeamActivity()`. The feed is for at-a-
 *  glance review, not auditing — older history lives in the per-module
 *  surfaces (Bookings, Payments, Customers). */
const MAX_TEAM_ACTIVITY = 50;

// ─── Source → label helpers ─────────────────────────────────────────────────

function bookingSourceSuffix(source: string | undefined): string {
    if (source === "front_desk") return " · via Front desk";
    if (source === "admin")      return " · via Admin team";
    if (source === "pos")        return " · via POS";
    return "";
}
function cancellationSourceSuffix(source: string | undefined): string {
    if (source === "front_desk") return " · by Front desk";
    if (source === "admin")      return " · by Admin team";
    if (source === "system")     return " · by System";
    return "";
}
function paymentSourceSuffix(source: string | undefined): string {
    if (source === "pos")   return " · via POS";
    if (source === "admin") return " · via Admin team";
    return "";
}

/** Friendly label for the verb-form attendance state used in feed copy. */
function attendanceLabel(status: string): string {
    if (status === "present")     return "present";
    if (status === "no_show")     return "as no-show";
    if (status === "late_cancel") return "as late-cancel";
    return status;
}
function attendanceIcon(status: string): ActivityIcon {
    if (status === "present")     return UserCheck01;
    if (status === "no_show")     return UserX01;
    if (status === "late_cancel") return UserX01;
    return UserCheck01;
}

/** Map an audit-log target type → tile icon. Keeps the feed's left-rail
 *  glyph row visually scannable (Tag for products, Building for branches,
 *  CoinsHand for payroll, Settings for the rest of config). */
function auditIcon(targetType: AuditLogEntry["targetType"]): ActivityIcon {
    switch (targetType) {
        case "customer":
        case "customer_plan":
        case "account":        return Users01;
        case "class_template": return Edit05;
        case "service":        return Edit05;
        case "appointment":    return CalendarCheck01;
        case "class_schedule": return CalendarCheck01;
        case "membership":
        case "package":
        case "gift_card":      return Tag01;
        case "promo_code":     return Ticket01;
        case "branch":
        case "room":           return Building01;
        case "marketing":      return Announcement01;
        case "staff":          return UserCheck01;
        // Staff & shift module (Phase 4F) — shift CRUD + blocked time CRUD
        // both surface here via the audit feed. Reuse the calendar glyph
        // since both events affect the staff schedule grid.
        case "shift":
        case "blocked_time":   return CalendarCheck01;
        case "pay_rate":
        case "payroll":        return CoinsHand;
        case "rating":         return Star01;
        case "settings":
        default:               return Settings01;
    }
}

/** Compose the description suffix when metadata enriches the audit copy
 *  (amounts, status, date ranges, etc.). Keeps it concise so the feed
 *  doesn't grow unwieldy. */
function auditMetadataSuffix(metadata?: AuditLogEntry["metadata"]): string {
    if (!metadata) return "";
    const bits: string[] = [];
    if (metadata.amount !== undefined)  bits.push(`AED ${metadata.amount}`);
    if (metadata.credits !== undefined) bits.push(`${metadata.credits} credits`);
    if (metadata.from && metadata.to)   bits.push(`${metadata.from} → ${metadata.to}`);
    if (metadata.status !== undefined)  bits.push(`status: ${metadata.status}`);
    if (metadata.entries !== undefined) bits.push(`${metadata.entries} entries`);
    if (metadata.reason && typeof metadata.reason === "string" && metadata.reason.length > 0)
        bits.push(`"${metadata.reason}"`);
    return bits.length > 0 ? ` · ${bits.join(" · ")}` : "";
}

/** Friendly role label used as a parenthetical actor suffix so the feed
 *  immediately shows WHO did the action. */
function auditActorRoleLabel(role: string): string {
    if (role === "admin")      return "Admin";
    if (role === "instructor") return "Instructor";
    if (role === "member")     return "Customer";
    return "Studio team";
}

// ─── Hook ───────────────────────────────────────────────────────────────────

/**
 * Live, ordered activity feed across customer + staff actions.
 *
 * Recomputes whenever any of the source slices mutate — so creating a new
 * booking through any surface (customer portal / POS / admin add-customer
 * flow) flips a fresh row into the dashboard widget AND the notifications
 * Team activity tab in the same render cycle.
 */
export function useTeamActivity(limit: number = MAX_TEAM_ACTIVITY): TeamActivityItem[] {
    const classBookings        = useAppStore(s => s.classBookings);
    const classSchedules       = useAppStore(s => s.classSchedules);
    const customers            = useAppStore(s => s.customers);
    const customerTransactions = useAppStore(s => s.customerTransactions);
    const auditLog             = useAppStore(s => s.auditLog);

    return useMemo(() => {
        // Build lookup maps once per recompute — keeps the per-row
        // resolution path O(1) so a few thousand rows in either slice
        // doesn't tank scroll perf.
        const customerById = new Map(customers.map(c => [c.id, c] as const));
        const scheduleById = new Map(classSchedules.map(s => [s.id, s] as const));

        const items: TeamActivityItem[] = [];

        function customerDisplayName(customerId: string): string {
            const c = customerById.get(customerId);
            return c ? `${c.firstName} ${c.lastName}`.trim() : "A customer";
        }
        function classDisplayName(scheduleId: string): string {
            return scheduleById.get(scheduleId)?.name ?? "a class";
        }

        // ─── Bookings + waitlist joins + cancellations ────────────────────
        for (const b of classBookings) {
            const customerName = customerDisplayName(b.customerId);
            const className    = classDisplayName(b.classScheduleId);

            // Booking creation — every row except the customer-self-
            // cancelled / late-cancel ones contributes a "booked" event
            // because the row was originally created BEFORE its status
            // flipped.
            if (b.bookingTime) {
                if (b.status === "booked") {
                    items.push({
                        id: `bk_${b.id}`,
                        name: customerName,
                        timeAgo: relativeTime(b.bookingTime),
                        description: `Booked ${className}${bookingSourceSuffix(b.bookingSource)}`,
                        icon: CalendarCheck01,
                        createdAt: b.bookingTime,
                    });
                } else if (b.status === "waitlisted") {
                    items.push({
                        id: `wl_${b.id}`,
                        name: customerName,
                        timeAgo: relativeTime(b.bookingTime),
                        description: `Joined waitlist for ${className}${bookingSourceSuffix(b.bookingSource)}`,
                        icon: CalendarCheck01,
                        createdAt: b.bookingTime,
                    });
                }
            }

            // Cancellation event — emitted whenever the row carries a
            // `cancelledAt` stamp, regardless of class-level vs. self
            // cancel (the source suffix already disambiguates intent).
            if (b.cancelledAt) {
                items.push({
                    id: `cx_${b.id}`,
                    name: customerName,
                    timeAgo: relativeTime(b.cancelledAt),
                    description: `Cancelled ${className}${cancellationSourceSuffix(b.cancelledSource)}`,
                    icon: CalendarCheck01,
                    createdAt: b.cancelledAt,
                });
            }

            // Attendance marking — the STAFF member is the focal name
            // (this is their action, not the customer's), with the
            // customer + class woven into the description. Stamped by
            // `updateAttendance` from `currentUser`, so when an
            // instructor marks attendance on /instructor/* the row
            // attributes correctly.
            if (b.attendanceMarkedAt && b.attendanceStatus !== "pending") {
                const actor = b.attendanceMarkedBy ?? "Studio team";
                items.push({
                    id: `at_${b.id}`,
                    name: actor,
                    timeAgo: relativeTime(b.attendanceMarkedAt),
                    description: `Marked ${customerName} ${attendanceLabel(b.attendanceStatus)} in ${className}`,
                    icon: attendanceIcon(b.attendanceStatus),
                    createdAt: b.attendanceMarkedAt,
                });
            }
        }

        // ─── Class-level cancellations ────────────────────────────────────
        //
        // A whole class being cancelled is a STAFF action (admin or the
        // instructor for the class). `schedule.cancelledBy` is populated
        // by `cancelClassSchedule` from `currentUser` — that's the
        // instructor's name when they cancel from /instructor/schedule,
        // and the admin's name when they cancel from /admin/schedule. The
        // actor goes in `name`; the description describes the action.
        for (const s of classSchedules) {
            if (!s.cancelledAt) continue;
            const actor = s.cancelledBy ?? "Studio team";
            items.push({
                id: `cs_class_${s.id}`,
                name: actor,
                timeAgo: relativeTime(s.cancelledAt),
                description: `Cancelled ${s.name} class on ${s.dayOfWeek} at ${s.displayTime}`,
                icon: SlashCircle01,
                createdAt: s.cancelledAt,
            });
        }

        // ─── Transactions (purchases + refunds) ───────────────────────────
        for (const t of customerTransactions) {
            const customerName = customerDisplayName(t.customerId);
            if (t.status === "complete" && t.createdAtISO) {
                items.push({
                    id: `tx_${t.id}`,
                    name: customerName,
                    timeAgo: relativeTime(t.createdAtISO),
                    description: `Purchased ${t.name} for AED ${t.amountAed}${paymentSourceSuffix(t.paymentSource)}`,
                    icon: CreditCard02,
                    createdAt: t.createdAtISO,
                });
            } else if (t.status === "refunded" && t.refundedAtISO) {
                items.push({
                    id: `rf_${t.id}`,
                    name: customerName,
                    timeAgo: relativeTime(t.refundedAtISO),
                    description: `Refund processed for ${t.name} — AED ${t.amountAed}${paymentSourceSuffix(t.paymentSource)}`,
                    icon: RefreshCw04,
                    createdAt: t.refundedAtISO,
                });
            }
        }

        // ─── New member signups ───────────────────────────────────────────
        for (const c of customers) {
            if (!c.createdAt) continue;
            items.push({
                id: `cs_${c.id}`,
                name: `${c.firstName} ${c.lastName}`.trim(),
                timeAgo: relativeTime(c.createdAt),
                description: "Signed up as a new member",
                icon: Users01,
                createdAt: c.createdAt,
            });
        }

        // ─── Audit log events ─────────────────────────────────────────────
        //
        // Every back-office mutation (customer profile edits, freezes, comp
        // credits, product CRUD, settings changes, marketing, payroll,
        // pay-rate assignment, etc.) flows through `recordAudit` and lands
        // here. The actor is the persona that performed the action — so
        // when an instructor edits their own profile, the row says "River
        // Teach (Instructor) · Updated own profile". When an admin
        // freezes a membership, it's "Alex Owen (Admin) · Froze Sara
        // Williams's plan".
        for (const a of auditLog) {
            const actor = `${a.actorName} (${auditActorRoleLabel(a.actorRole)})`;
            const description = `${a.action} "${a.targetName}"${auditMetadataSuffix(a.metadata)}`;
            items.push({
                id: `au_${a.id}`,
                name: actor,
                timeAgo: relativeTime(a.createdAt),
                description,
                icon: auditIcon(a.targetType),
                createdAt: a.createdAt,
            });
        }

        // Newest first.
        items.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
        return items.slice(0, limit);
    }, [classBookings, classSchedules, customers, customerTransactions, auditLog, limit]);
}

// ─── Row component ──────────────────────────────────────────────────────────

// Row chrome MIRRORS `NotificationRow` in `/admin/notifications/page.tsx`
// — same icon tile size + radius + shadow, same 16px font scale, same
// hover treatment — so the Team activity tab feels identical to the All /
// Bookings / Payments tabs sitting next to it.
export function TeamActivityRow({ item }: { item: TeamActivityItem }) {
    const Icon = item.icon;
    return (
        <div className="w-full flex gap-3 items-center py-1.5 -mx-2 px-2 rounded-[8px] hover:bg-[#f9fafb] transition-colors">
            {/* Featured icon tile (48px) — matches NotificationRow */}
            <div className="shrink-0 w-12 h-12 rounded-[10px] bg-[#f9fafb] border-1 border-[#e4e7ec] flex items-center justify-center shadow-[0px_1.481px_1.481px_rgba(0,0,0,0.04)]">
                <Icon className="w-6 h-6 text-[#475467]" />
            </div>
            {/* Text block — same 16px scale as NotificationRow */}
            <div className="flex-1 min-w-0 flex flex-col gap-[2px]">
                <div className="flex items-baseline gap-[6px] flex-wrap">
                    <p className="text-[16px] font-semibold leading-[24px] text-[#344054]">
                        {item.name}
                    </p>
                    <p className="text-[16px] font-normal leading-[24px] text-[#667085]">
                        {item.timeAgo}
                    </p>
                </div>
                <p className="text-[16px] font-normal leading-[24px] text-[#475467]">
                    {item.description}
                </p>
            </div>
        </div>
    );
}
