// ─────────────────────────────────────────────────────────────────────────────
// Onra Studio — Reports · Excel export (SheetJS)
// ─────────────────────────────────────────────────────────────────────────────
//
// Produces proper `.xlsx` files (not CSV renamed) with number formatting
// and a self-describing metadata sheet. The client explicitly asked for
// Excel export as a required feature (see new-prd/reports-implementation
// -plan.md §2.6).
//
// Two shapes (mirroring the CSV exporter):
//   1. exportListXlsx — flat list, one sheet + a metadata sheet.
//   2. exportPivotXlsx — matrix, one sheet + a metadata sheet.
//
// Excel column formats used:
//   - currency  → "AED" _-#,##0                (leading AED, thousands sep)
//   - number    → #,##0
//   - percent   → 0.00%
//   - date      → yyyy-mm-dd
//
// SheetJS lets us set per-cell number format via `t: "n"` + `z: format`.
// Text cells use `t: "s"`. See https://docs.sheetjs.com for the cell type
// reference.

import * as XLSX from "xlsx";
import type { ColumnDef, PivotResult } from "./types";

// ─── Excel format strings ─────────────────────────────────────────────────

const FMT_CURRENCY = '"AED" #,##0';
const FMT_NUMBER   = "#,##0";
const FMT_PERCENT  = "0.00%";
const FMT_DATE     = "yyyy-mm-dd";

/** Map a column kind to its default Excel number format. */
function excelFormatFor(kind: ColumnDef["kind"]): string | undefined {
    if (kind === "currency") return FMT_CURRENCY;
    if (kind === "number")   return FMT_NUMBER;
    if (kind === "percent")  return FMT_PERCENT;
    if (kind === "date")     return FMT_DATE;
    return undefined; // text, id, status → no format
}

/** Build a SheetJS cell from a value + column kind. Numeric kinds use `t:
 *  "n"` so Excel can sum/filter. Percentages are stored as decimals
 *  (0.15 = 15%) matching how spreadsheet apps model them. */
function cellFor(value: unknown, kind: ColumnDef["kind"]): XLSX.CellObject {
    if (value === null || value === undefined || value === "") {
        return { t: "s", v: "" };
    }
    if (kind === "currency" || kind === "number") {
        const n = Number(value);
        if (!Number.isFinite(n)) return { t: "s", v: String(value) };
        return { t: "n", v: n, z: excelFormatFor(kind) };
    }
    if (kind === "percent") {
        const n = Number(value);
        if (!Number.isFinite(n)) return { t: "s", v: String(value) };
        return { t: "n", v: n / 100, z: FMT_PERCENT };
    }
    if (kind === "date") {
        const s = String(value).slice(0, 10);
        return { t: "s", v: s, z: FMT_DATE };
    }
    return { t: "s", v: String(value) };
}

// ─── Metadata sheet ───────────────────────────────────────────────────────

export interface ExportMetadata {
    reportTitle: string;
    /** Human-readable date range applied. E.g. "This year", "Last 30 days",
     *  or "2026-01-01 → 2026-06-30". */
    dateRange: string;
    /** Selected filters (Location, custom filters, etc). Free text. */
    filters?: string;
    /** Selected period bucket. Only meaningful for pivot exports. */
    period?: string;
    /** Selected breakdown dimension. Only meaningful for pivot exports. */
    breakdown?: string;
    /** ISO timestamp when the export ran. */
    exportedAtISO: string;
    /** Total rows / groups in the exported view. */
    rowCount: number;
}

/** Build a self-describing "Metadata" worksheet — always added as the
 *  SECOND sheet so the export file explains itself to future readers. */
function buildMetadataSheet(meta: ExportMetadata): XLSX.WorkSheet {
    const rows: (string | number)[][] = [
        ["Report",       meta.reportTitle],
        ["Date range",   meta.dateRange],
        ["Filters",      meta.filters ?? "—"],
        ["Period",       meta.period   ?? "—"],
        ["Breakdown",    meta.breakdown ?? "—"],
        ["Rows",         meta.rowCount],
        ["Exported at",  meta.exportedAtISO],
        ["Generated by", "Onra Studio · Reports module"],
    ];
    return XLSX.utils.aoa_to_sheet(rows);
}

// ─── List-mode export ─────────────────────────────────────────────────────

export interface ExportListXlsxOpts {
    columns: ColumnDef[];
    rows: readonly Record<string, unknown>[];
    filename: string;
    meta: ExportMetadata;
    /** Sheet name in the workbook (defaults to "Report" — 31 char max). */
    sheetName?: string;
    /** Add a Total row for numeric columns at the bottom. */
    includeTotalRow?: boolean;
}

export function exportListXlsx(opts: ExportListXlsxOpts): void {
    const { columns, rows, filename, meta, sheetName = "Report", includeTotalRow = true } = opts;

    // Build cell matrix — header + data + optional total.
    const headers: XLSX.CellObject[] = columns.map(c => ({ t: "s", v: c.label }));
    const dataMatrix: XLSX.CellObject[][] = [headers];

    for (const r of rows) {
        dataMatrix.push(columns.map(c => cellFor(r[c.key], c.kind)));
    }

    if (includeTotalRow) {
        const totalRow: XLSX.CellObject[] = columns.map((c, i) => {
            if (i === 0) return { t: "s", v: "Total" };
            if (c.kind !== "currency" && c.kind !== "number") return { t: "s", v: "" };
            let sum = 0;
            for (const r of rows) {
                const n = Number(r[c.key]);
                if (Number.isFinite(n)) sum += n;
            }
            return { t: "n", v: sum, z: excelFormatFor(c.kind) };
        });
        dataMatrix.push(totalRow);
    }

    const sheet = XLSX.utils.aoa_to_sheet(dataMatrix);
    // Column widths — text cols get 22, number/date get 14. Excel treats
    // the wch as characters, ~10px per char in default font.
    sheet["!cols"] = columns.map(c => {
        const isText = c.kind === "text" || c.kind === "id" || c.kind === "status";
        return { wch: isText ? Math.max(22, (c.minWidth ?? 200) / 9) : 14 };
    });

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, sheet,                    sheetName.slice(0, 31));
    XLSX.utils.book_append_sheet(wb, buildMetadataSheet(meta), "Metadata");

    XLSX.writeFile(wb, filename.endsWith(".xlsx") ? filename : `${filename}.xlsx`);
}

// ─── Pivot-mode export ────────────────────────────────────────────────────

export interface ExportPivotXlsxOpts {
    rowHeader: string;
    colHeaders: string[];
    pivot: PivotResult;
    filename: string;
    meta: ExportMetadata;
    sheetName?: string;
    /** Whether pivot cells should render as currency (default) or plain number. */
    valueKind?: "currency" | "number";
}

export function exportPivotXlsx(opts: ExportPivotXlsxOpts): void {
    const { rowHeader, colHeaders, pivot, filename, meta, sheetName = "Report", valueKind = "currency" } = opts;
    const valueFmt = excelFormatFor(valueKind);

    // Cell builder for numeric matrix cells.
    const numCell = (n: number): XLSX.CellObject => ({ t: "n", v: Math.round(n), z: valueFmt });

    const matrix: XLSX.CellObject[][] = [];

    // Row 1 — [rowHeader, ...colHeaders, "Total"].
    matrix.push([
        { t: "s", v: rowHeader },
        ...colHeaders.map(h => ({ t: "s", v: h } as XLSX.CellObject)),
        { t: "s", v: "Total" },
    ]);

    // Data rows.
    for (const rk of pivot.rowKeys) {
        const cells: XLSX.CellObject[] = [{ t: "s", v: rk }];
        for (const ck of pivot.colKeys) {
            cells.push(numCell(pivot.matrix[rk]?.[ck] ?? 0));
        }
        cells.push(numCell(pivot.rowTotals[rk] ?? 0));
        matrix.push(cells);
    }

    // Column-totals row.
    const totalRow: XLSX.CellObject[] = [{ t: "s", v: "Total" }];
    for (const ck of pivot.colKeys) totalRow.push(numCell(pivot.colTotals[ck] ?? 0));
    totalRow.push(numCell(pivot.grandTotal));
    matrix.push(totalRow);

    // Delta row.
    const deltaRow: XLSX.CellObject[] = [{ t: "s", v: "Period change (%)" }];
    for (const d of pivot.columnDeltasPct) {
        if (d === null) deltaRow.push({ t: "s", v: "" });
        else deltaRow.push({ t: "n", v: d / 100, z: FMT_PERCENT });
    }
    deltaRow.push({ t: "s", v: "" });
    matrix.push(deltaRow);

    const sheet = XLSX.utils.aoa_to_sheet(matrix);
    sheet["!cols"] = [
        { wch: 24 },                              // row header
        ...colHeaders.map(() => ({ wch: 14 })),   // period columns
        { wch: 14 },                              // total column
    ];

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, sheet,                    sheetName.slice(0, 31));
    XLSX.utils.book_append_sheet(wb, buildMetadataSheet(meta), "Metadata");

    XLSX.writeFile(wb, filename.endsWith(".xlsx") ? filename : `${filename}.xlsx`);
}
